name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: npm ci
        run: npm ci
      - name: Type Coverage
        run: npm run type-coverage-report
      - name: Artifact - Type Coverage Report
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: type-coverage-report
          path: coverage-ts
          if-no-files-found: error
