name: CI

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: npm install
        run: npm install
      - name: Publish VSCode Extension
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
